In [1]:
from pathlib import Path
from ai_news_digest.config import Settings
from ai_news_digest.pipeline import collect_articles, rank_and_select, summarize_and_build, _get_llm
from datetime import datetime

In [2]:
# Parámetros de corrida
DAYS = 30
TOP_N = 20 ##15
#ENSURE_SOURCES = [] 
ENSURE_SOURCES = ['Kdnuggets.com']
MONTH_NAME = "marzo_26"
LANG = "es"

ts = datetime.now().strftime("%Y%m%d_%H%M%S")
OUT_PATH = "outputs/Highlights_AI" + "_"+ MONTH_NAME + "_" + ts +".txt"
print(f"Output path: {OUT_PATH}")

settings = Settings()

Output path: outputs/Highlights_AI_marzo_26_20260331_095215.txt

In [3]:
# Cliente LLM compartido — acumula tokens entre ranking y summary
llm_client = _get_llm(settings)
print(f"LLM client: {type(llm_client).__name__ if llm_client else 'None'}")

Trying OpenRouterClient...
LLM client: OpenRouterClient

In [4]:
settings

Settings(newsapi_key='7061081eafba4ec4919593e8560e6307', openai_api_key='', openai_model_relevance='gpt-4o-mini', openai_model_summary='gpt-4o-mini', openrouter_api_key='OPENROUTER_KEY_REDACTED', openrouter_model_relevance='nvidia/nemotron-3-super-120b-a12b:free', openrouter_model_summary='stepfun/step-3.5-flash:free', azure_api_key='', azure_endpoint='', azure_deployment_relevance='', azure_deployment_summary='', azure_api_version='2024-02-01')

## Articles Collect

In [5]:
print("🔎 [1/4] Recolectando artículos...")
df_all = collect_articles(settings, days=DAYS)
print(f"   → Artículos recolectados: {len(df_all)}")
if df_all.empty:
        print("   ⚠️  No se encontraron artículos.")

df_all.head(5)

🔎 [1/4] Recolectando artículos...
Collecting articles with NewsAPI...
Total NewsAPI domains used: 125
From date:  2026-03-01 to date:  2026-03-31
------Artículos en Ingles recolectados con NewsAPI: 54
Total NewsAPI domains used: 125
From date:  2026-03-01 to date:  2026-03-31
------Artículos en Español recolectados con NewsAPI: 1
Collecting articles with TechCrunch...
Procesando https://techcrunch.com/category/artificial-intelligence/...
Procesando https://techcrunch.com/category/artificial-intelligence/page/2/...
Procesando https://techcrunch.com/category/artificial-intelligence/page/3/...
Procesando https://techcrunch.com/category/artificial-intelligence/page/4/...
Procesando https://techcrunch.com/category/artificial-intelligence/page/5/...
------Artículos recolectados con TechCrunch: 152
   → Artículos recolectados: 207

,fuente,titulo,url,fecha,contenido
0,The Verge,Why people really hate AI,https://www.theverge.com/podcast/897900/ai-tru...,2026-03-20T13:27:53Z,is editor-at-large and Vergecast co-host with ...
1,The Verge,Inside the secret meeting that led to the AI p...,https://www.theverge.com/ai-artificial-intelli...,2026-03-04T06:06:52Z,"In early January, a group of 90 or so politica..."
2,The Verge,DLSS 5: Has Nvidia’s AI graphics technology go...,https://www.theverge.com/games/896518/nvidia-d...,2026-03-18T12:25:06Z,Nvidia has revealed a new “3D guided neural re...
3,The Verge,Future Sony PlayStation games will use AI to i...,https://www.theverge.com/news/898283/future-so...,2026-03-20T19:49:59Z,is a senior editor and founding member of The ...
4,The Verge,Amazon is making an Alexa phone,https://www.theverge.com/tech/897915/amazon-tr...,2026-03-20T13:42:51Z,"Over 10 years after shelving the Fire Phone, A..."

In [6]:
df_all.fuente.value_counts()

fuente
TechCrunch    152
The Verge      34
Wired          20
BBC News        1
Name: count, dtype: int64

In [7]:
df_all.to_csv("outputs/all_articles_mar_26_v2.csv", index=False)

## Articles Ranking

In [ ]:
# import pandas as pd
# df_all = pd.read_csv("outputs/all_articles_mar_26.csv")
# df_all.fuente.value_counts()
# df_all.head(5)

,fuente,titulo,url,fecha,contenido
0,The Verge,Why people really hate AI,https://www.theverge.com/podcast/897900/ai-tru...,2026-03-20T13:27:53Z,is editor-at-large and Vergecast co-host with ...
1,The Verge,Inside the secret meeting that led to the AI p...,https://www.theverge.com/ai-artificial-intelli...,2026-03-04T06:06:52Z,"In early January, a group of 90 or so politica..."
2,The Verge,DLSS 5: Has Nvidia’s AI graphics technology go...,https://www.theverge.com/games/896518/nvidia-d...,2026-03-18T12:25:06Z,Nvidia has revealed a new “3D guided neural re...
3,The Verge,Future Sony PlayStation games will use AI to i...,https://www.theverge.com/news/898283/future-so...,2026-03-20T19:49:59Z,is a senior editor and founding member of The ...
4,The Verge,Amazon is making an Alexa phone,https://www.theverge.com/tech/897915/amazon-tr...,2026-03-20T13:42:51Z,"Over 10 years after shelving the Fire Phone, A..."

In [8]:
print("📊 [2/4] Rankeando artículos por relevancia...")
df_top = rank_and_select(df_all, settings, top_n=TOP_N, ensure_source=ENSURE_SOURCES, llm_client=llm_client)
print(f"   → Seleccionados top {len(df_top)} artículos")
if llm_client and hasattr(llm_client, "token_summary"):
    print("   ", llm_client.token_summary())

📊 [2/4] Rankeando artículos por relevancia...
ensure_source: ['Kdnuggets.com']
Using LLM: OpenRouterClient
client: <ai_news_digest.llm.openrouter.OpenRouterClient object at 0x00000256CBB50E90>
   Batch LLM scoring: 207 artículos en 11 batches de 20...
   Batch 1/11...
   Batch 2/11...
   Batch 3/11...
   Batch 4/11...
   Batch 5/11...
   Batch 6/11...
   Batch 7/11...
   Batch 8/11...
   Batch 9/11...
   Batch 10/11...
   Batch 11/11...
   Scoring: 207 con LLM, 0 con heurística
   → Seleccionados top 20 artículos
    Tokens usados — prompt: 16,332 | completion: 29,943 | total: 46,275

C:\Users\clara.o.villalba\Documents\Medium\MediumAutomation-1\ai_news_digest\pipeline.py:158: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_limited = df_final.groupby('fuente', group_keys=False).apply(lambda x: x.head(10)).reset_index(drop=True)

In [9]:
df_top.fuente.value_counts()

fuente
TechCrunch    10
Wired          6
The Verge      4
Name: count, dtype: int64

In [10]:
df_top.to_csv("outputs/top_ranked_articles_mar_26_v2.csv", index=False)

## Article Sumarize

In [11]:
# import pandas as pd
# df_top = pd.read_csv("outputs/top_ranked_articles_mar_26.csv")
# print(df_top.fuente.value_counts())
# df_top.head(5)

In [12]:
print("📝 [3/4] Generando resúmenes y armando artículo...")
article, df_res = summarize_and_build(df_top, settings, month_name=MONTH_NAME, lang=LANG, llm_client=llm_client)
print("   → Resúmenes generados")
if llm_client and hasattr(llm_client, "token_summary"):
    print("   ", llm_client.token_summary())

📝 [3/4] Generando resúmenes y armando artículo...
Using LLM for summarization: OpenRouterClient
   [1/20] Resumiendo: Mantis Biotech is making ‘digital twins’ of humans to help solve medic...
   [1/20] OK
   [2/20] Resumiendo: ByteDance’s new AI video generation model, Dreamina Seedance 2.0, come...
Error summarizing 'ByteDance’s new AI video generation model, Dreamina Seedance': 429 Client Error: Too Many Requests for url: https://openrouter.ai/api/v1/chat/completions
   [3/20] Resumiendo: Google unveils TurboQuant, a new AI memory compression algorithm — and...
   [3/20] OK
   [4/20] Resumiendo: Nvidia is quietly building a multibillion-dollar behemoth to rival its...
   [4/20] OK
   [5/20] Resumiendo: ByteDance’s AI Ambitions Are Being Hampered by Compute Restraints and ...
   [5/20] OK
   [6/20] Resumiendo: Cohere launches an open source voice model specifically for transcript...
   [6/20] OK
   [7/20] Resumiendo: Nvidia’s DLSS 5 uses generative AI to boost photorealism in video game...
   [7/20] OK
   [8/20] Resumiendo: DLSS 5: Has Nvidia’s AI graphics technology gone too far?...
   [8/20] OK
   [9/20] Resumiendo: Spotify tests new tool to stop AI slop from being attributed to real a...
   [9/20] OK
   [10/20] Resumiendo: Google launches Lyria 3 Pro music generation model...
   [10/20] OK
   [11/20] Resumiendo: Mistral releases a new open source model for speech generation...
   [11/20] OK
   [12/20] Resumiendo: Startup Gimlet Labs is solving the AI inference bottleneck in a surpri...
   [12/20] OK
   [13/20] Resumiendo: Palantir Demos Show How the Military Could Use AI Chatbots to Generate...
   [13/20] OK
   [14/20] Resumiendo: At Palantir’s Developer Conference, AI Is Built to Win Wars...
   [14/20] OK
   [15/20] Resumiendo: Now everyone in the US is getting Google’s personalized Gemini AI...
Error summarizing 'Now everyone in the US is getting Google’s personalized Gemi': 429 Client Error: Too Many Requests for url: https://openrouter.ai/api/v1/chat/completions
   [16/20] Resumiendo: Nvidia Is Planning to Launch an Open-Source AI Agent Platform...
   [16/20] OK
   [17/20] Resumiendo: What AI Models for War Actually Look Like...
   [17/20] OK
   [18/20] Resumiendo: Bespoke AI models are the next big thing in filmmaking...
   [18/20] OK
   [19/20] Resumiendo: Google Search is now using AI to replace headlines...
   [19/20] OK
   [20/20] Resumiendo: Meet the Tech Reporters Using AI to Help Write and Edit Their Stories...
   [20/20] OK
   → Resúmenes generados
    Tokens usados — prompt: 30,416 | completion: 49,409 | total: 79,825

In [13]:
df_res.resumen

0     **Mantis Biotech desarrolla 'gemelos digitales...
1     (Sin LLM) OpenAI may be dialing back its effor...
2     **Google presenta TurboQuant: el algoritmo de ...
3     **Nvidia Construye en Silencio un Gigante de R...
4     **ByteDance lanza Seedance 2.0, pero las restr...
5     **Cohere presenta Transcribe: modelo de voz de...
6     **Nvidia Presenta DLSS 5: IA Generativa para E...
7     **DLSS 5: La IA de Nvidia redibuja el renderiz...
8     **Spotify lanza herramienta para proteger perf...
9     **Google presenta Lyria 3 Pro: generación musi...
10    **Mistral impulsa la competencia en síntesis d...
11    **Título:** Gimlet Labs resuelve el cuello de ...
12    **Claude en el Campo de Batalla: Cómo Palantir...
13    **Palantir apuntala su dominio en IA militar c...
14    (Sin LLM) Google announced on Tuesday that all...
15    **Título: Nvidia apuesta por los agentes autón...
16    **Título: Smack Technologies impulsa la IA mil...
17    **Los modelos de IA a medida marcan un nuevo r...
18    **Google Search sustituye titulares periodísti...
19    **Periodistas Tecnológicos Integran IA en su F...
Name: resumen, dtype: object

In [14]:
article

'# 🧠 Los Highlights de marzo_26 en Inteligencia Artificial\n\nTe compartimos las noticias más destacadas del mes.\n\n### **Mantis Biotech desarrolla \'gemelos digitales\' humanos para superar la escasez de datos biomédicos**\n\n![**Mantis Biotech desarrolla \'gemelos digitales\' humanos para superar la escasez de datos biomédicos**](https://techcrunch.com/wp-content/uploads/2019/09/brain_pills.jpg?resize=1200,899)\n\n**Mantis Biotech desarrolla \'gemelos digitales\' humanos para superar la escasez de datos biomédicos**\n\nEl potencial de los grandes modelos de lenguaje (LLM) entrenados con vastos conjuntos de datos para revolucionar la investigación biomédica —desde la genómica y el descubrimiento de fármacos hasta el diagnóstico en tiempo real— choca con un cuello de botella fundamental: la escasez de datos fiables y representativos en casos límite, como enfermedades raras o condiciones atípicas. Esta brecha de disponibilidad de datos limita la capacidad de estos sistemas para generalizar y ofrecer predicciones robustas en escenarios clínicos complejos.\n\nFrente a este desafío, la startup neoyorquina Mantis Biotech anuncia el desarrollo de una plataforma que crea "gemelos digitales" del cuerpo humano. Su solución integra fuentes de información dispares —desde imágenes médicas y sensores biométricos hasta registros de entrenamiento y textbooks— para generar conjuntos de datos sintéticos de alta fidelidad. Estos gemelos son modelos predictivos basados en física que simulan la anatomía, la fisiología y el comportamiento. El flujo de trabajo de la plataforma utiliza un sistema impulsado por LLM para enrutar, validar y sintetizar los diferentes flujos de datos, los cuales luego se procesan a través de un motor de física que genera representaciones detalladas, listas para entrenar modelos predictivos avanzados.\n\nLa relevancia de esta tecnología radica en su aplicabilidad transversal. Según explicó Georgia Witchel, fundadora y CEO de Mantis, estos gemelos podrían utilizarse para estudiar y probar procedimientos médicos, entrenar robots quirúrgicos, predecir problemas de salud o incluso patrones de comportamiento. Un ejemplo concreto sería predecir la probabilidad de que un atleta específico de la NFL sufra una lesión en el tendón de Aquiles, integrando datos de su rendimiento reciente, carga de entrenamiento, dieta y tiempo de actividad. A largo plazo, la capacidad de generar datos sintéticos representativos podría acelerar drásticamente el descubrimiento de fármacos, permitir simulaciones clínicas más seguras y abrir la puña a una medicina verdaderamente personalizada, al ofrecer un campo de pruebas virtual para hipótesis donde los datos del mundo real son escasos o inexistentes.\n\nSeguí leyendo en este enlace: https://techcrunch.com/2026/03/30/mantis-biotech-is-making-digital-twins-of-humans-to-help-solve-medicines-data-availability-problem/\n\n---\n\n### ByteDance’s new AI video generation model, Dreamina Seedance 2.0, comes to CapCut\n\n![ByteDance’s new AI video generation model, Dreamina Seedance 2.0, comes to CapCut](https://techcrunch.com/wp-content/uploads/2026/03/imgi_30_7d51e3a4c1434d7f9b2708a619f3783ftplv-2zwwjm3azk-image.webp?resize=1200,853)\n\n(Sin LLM) OpenAI may be dialing back its efforts in the video generation market with theshutdown of its Sora app, but ByteDance on Thursday confirmed that its new audio and video model,Dreamina Seedance 2.0, is now rolling out in its editing platform,CapCut.\nByteDance says the model allows creators to draft, edit, and sync video and audio content by using prompts, images, or reference videos.\nThe phased rol...\nSeguí leyendo: https://techcrunch.com/2026/03/26/bytedances-new-ai-video-generation-model-dreamina-seedance-2-0-comes-to-capcut/\n\n---\n\n### **Google presenta TurboQuant: el algoritmo de compresión de memoria para IA que revive el legado de ‘Pied Piper’**\n\n![**Google presenta TurboQuant: el algoritmo de compresión de memoria para IA que revive el legado de ‘Pied Piper’**](https://techcrunch.com/wp-content/uploads/2017/05/section_homepage_bg_2.jpg?resize=1200,675)\n\n**Google presenta TurboQuant: el algoritmo de compresión de memoria para IA que revive el legado de ‘Pied Piper’**\n\nEl anuncio de Google Research sobre un nuevo algoritmo de compresión de memoria para sistemas de inteligencia artificial ha desatado una ola de comentarios en redes sociales que lo bautizaron de inmediato como el “Pied Piper” del mundo real. La referencia es inevitable: al igual que la ficticia startup de la serie *Silicon Valley*, cuyas innovaciones se centraban en una compresión de datos casi sin pérdidas, TurboQuant promete una reducción drástica en la huella de memoria de los modelos de IA sin sacrificar precisión. Este paralelismo cultural subraya la magnitud del problema técnico que aborda: la creciente demanda de memoria (RAM y caché) que limita la eficiencia y escalabilidad de los grandes modelos de lenguaje y otros sistemas de IA.\n\nEl desarrollo, detallado en un estudio que será presentado en la conferencia ICLR 2026, introduce dos métodos clave. El primero, **PolarQuant**, es una técnica de cuantización vectorial que permite comprimir los tensores (las estructuras de datos fundamentales en el entrenamiento y ejecución de IA) de manera extremadamente eficiente. El segundo, **QJL**, es un método de entrenamiento y optimización que garantiza que esta compresión agresiva no degrade el rendimiento del modelo. Según los investigadores, la combinación de ambos en el framework **TurboQuant** logra aliviar cuellos de botella críticos en el procesamiento de IA, permitiendo que los modelos “recuerden” más información con un espacio de memoria significativamente menor. Los resultados iniciales reportan un puntaje de eficiencia **Weissman Score de 5.2**, una métrica que evalúa la relación entre tasa de compresión y fidelidad de los datos.\n\nLa relevancia de este avance es estratégica para la industria. La expansión descontrolada de los requisitos de memoria de la IA es un obstáculo mayor para la democratización de modelos más grandes, encarece la infraestructura de nube y limita la implementación en dispositivos edge. Una compresión efectiva como la que promete TurboQuant podría reducir costos operativos, acelerar los tiempos de inferencia y permitir el despliegue de modelos avanzados en hardware con recursos más limitados. Aunque su implementación práctica a escala industrial aún requiere validación, el interés generado —junto con la inevitable comparación con la ficción televisiva— señala que la solución de Google a este viejo problema de la computación ha capturado la atención de todo el ecosistema tecnológico.\n\nSeguí leyendo en este enlace: https://techcrunch.com/2026/03/25/google-turboquant-ai-memory-compression-silicon-valley-pied-piper/\n\n---\n\n### **Nvidia Construye en Silencio un Gigante de Redes que Desafía a su Negocio de Chips**\n\n![**Nvidia Construye en Silencio un Gigante de Redes que Desafía a su Negocio de Chips**](https://techcrunch.com/wp-content/uploads/2024/12/GettyImages-2183848584.jpg?resize=1200,800)\n\n**Nvidia Construye en Silencio un Gigante de Redes que Desafía a su Negocio de Chips**\n\nLa visión del CEO de Nvidia, Jensen Huang, de anticiparse al mercado se ha convertido en una constante. Si en 2010 impulsó el desarrollo de chips específicos para IA con años de ventaja, una decisión estratégica similar en 2020, con la adquisición de Mellanox Technologies, ha dado lugar a una de las divisiones de más rápido crecimiento y mayor rentabilidad de la compañía, aunque con menor atención mediática que su negocio histórico de GPU. Esta unidad, dedicada a la infraestructura de red para centros de datos, ha evolucionado hasta convertirse en el segundo motor de ingresos de Nvidia, solo por detrás de la división de cómputo.\n\nLos resultados financieros recientes muestran un crecimiento explosivo: la división reportó 11.000 millones de dólares en el último trimestre, un aumento interanual del 267%, y superó los 31.000 millones de dólares en el año completo. Este desempeño se sustenta en un portafolio tecnológico integrado que incluye la interfaz NVLink para la comunicación entre GPUs, los conmutadores y sistemas de red InfiniBand, la plataforma Ethernet Spectrum-X optimizada para cargas de IA y switches con óptica co-empaquetada. En conjunto, estas tecnologías constituyen los componentes esenciales para construir lo que Nvidia denomina una "fábrica de IA": un centro de datos especializado en el entrenamiento de modelos de IA a gran escala.\n\nLa magnitud del éxito es evidente al compararlo con actores consolidados. Según analistas, los 11.000 millones de dólares trimestrales de Nvidia en redes superan prácticamente la facturación anual total de Cisco en su negocio de networking. Esta división, nacida de una compra estratégica, no solo complementa la oferta de chips, sino que posiciona a Nvidia como un proveedor de infraestructura de extremo a extremo para la era de la IA, reduciendo su dependencia de un solo producto y creando un ecosistema tecnológico profundamente integrado y de alto valor. Su relevancia radica en que transforma a la compañía de un fabricante de componentes a un arquitecto de soluciones completas para el centro de datos inteligente.\n\nSeguí leyendo en este enlace: https://techcrunch.com/2026/03/18/nvidia-networking-division-building-a-multibillion-dollar-behemoth-to-rival-its-chips-business/\n\n---\n\n### **ByteDance lanza Seedance 2.0, pero las restricciones de acceso y los derechos de autor frenan su expansión global**\n\n![**ByteDance lanza Seedance 2.0, pero las restricciones de acceso y los derechos de autor frenan su expansión global**](https://media.wired.com/photos/69a8cd045c3afa23e264984b/191:100/w_1280,c_limit/Made-In-China-ByteDance-AI-Ambitions-Business-1582149003.jpg)\n\n**ByteDance lanza Seedance 2.0, pero las restricciones de acceso y los derechos de autor frenan su expansión global**\n\nEn el competitivo panorama de la inteligencia artificial generativa, ByteDance ha dado un golpe significativo con el lanzamiento de Seedance 2.0, una versión mejorada de su modelo de generación de video. Presentado a principios de febrero, este avance ha generado un impacto considerable en el ecosistema tecnológico chino, incluso entre quienes antes escuchaban con escepticismo las capacidades de la IA para crear contenido audiovisual. Figuras prominentes como Feng Ji, fundador del estudio Game Science (creador del éxito mundial *Black Myth: Wukong*), han expresado su asombro, señalando que la tecnología plantea desafíos inminentes para los marcos regulatorios de derechos de autor y moderación de contenido en China. Por su parte, Pan Tianhong, líder de un estudio de producción profesional con más de 15 millones de seguidores, destacó que el modelo "piensa como un director", superando claramente a las alternativas preexistentes en el mercado.\n\nSin embargo, el alcance de Seedance 2.0 está severamente limitado por restricciones de acceso. Por ahora, ByteDance solo permite probar el modelo a usuarios existentes de sus aplicaciones de IA para el mercado doméstico chino, como Doubao, Jimeng o Spark, bloqueando así el acceso internacional. Esta estrategia cerrada ha generado un mercado secundario de cuentas revendidas a entusiastas en el extranjero. Un indicio de posible apertura surgió esta semana con la actualización de su plataforma API y la divulgación de precios: según estimaciones de *IT Home*, generar un video de hasta 15 segundos, el límite actual, costaría poco más de 2 dólares.\n\nMás allá de las barreras de acceso, el desarrollo de ByteDance se inscribe en un contexto de tensiones geopolíticas y técnicas. Las ambiciones de la compañía en IA se ven coartadas por las restricciones al acceso a capacidad de computación (compute) de alta gama, un recurso crítico para entrenar modelos avanzados, y por la incertidumbre regulatoria en torno a la propiedad intelectual del contenido generado. Seedance 2.0 ejemplifica la rápida evolución de la IA china, pero su trayectoria futura dependerá tanto de su capacidad para sortear limitaciones técnicas como de cómo los legisladores aborden los vacíos legales que su propia innovación expone. Seguí leyendo en este enlace: https://www.wired.com/story/made-in-china-bytedances-ai-ambitions-are-being-hampered-by-compute-restraints/\n\n---\n\n### **Cohere presenta Transcribe: modelo de voz de código abierto optimizado para transcripción**\n\n![**Cohere presenta Transcribe: modelo de voz de código abierto optimizado para transcripción**](https://techcrunch.com/wp-content/uploads/2026/03/260325_TranscribeLaunch_Hero.jpeg?resize=1200,600)\n\n**Cohere presenta Transcribe: modelo de voz de código abierto optimizado para transcripción**\n\nLa empresa de inteligencia artificial empresarial Cohere dio un paso significativo en el ámbito del procesamiento de lenguaje hablado con el lanzamiento de su primer modelo de voz, denominado Transcribe. Este sistema, de arquitectura relativamente ligera con 2 mil millones de parámetros, está diseñado específicamente para tareas de transcripción automática, como la toma de notas y el análisis de discurso, y se distribuye como software de código abierto. Su diseño permite su despliegue en hardware de consumo, como GPUs de gama media, facilitando el auto-hospedaje para organizaciones y desarrolladores.\n\nTranscribe soporta un total de 14 idiomas, entre ellos español, inglés, francés, alemán, portugués, chino y árabe. Según métricas públicas en el benchmark Hugging Face Open ASR, el modelo logra una tasa de error de palabras (WER) promedio de 5.42, superando a competidores establecidos como Zoom Scribe v1, IBM Granite 4.0 1B y ElevenLabs Scribe v2. En evaluaciones humanas sobre precisión, coherencia y usabilidad de las transcripciones, obtuvo una tasa de victoria promedio del 61% frente a otros modelos, aunque mostró un rendimiento inferior en portugués, alemán y español. En eficiencia, puede procesar 525 minutos de audio en un solo minuto, una cifra destacada para su clase.\n\nEl lanzamiento responde a la creciente demanda de aplicaciones de dictado y notas inteligentes, un sector donde herramientas como Granola o Wispr Flow están ganando tracción. Cohere integrará Transcribe en su plataforma de orquestación de agentes empresariales, North, y lo ofrecerá gratuitamente a través de su API, además de incluirlo en Model Vault, su plataforma de inferencia gestionada. Este movimiento amplía su cartera de productos más allá de los modelos de texto, posicionándose en un mercado de reconocimiento de voz en expansión. El anuncio se produce en un momento de fuerte crecimiento para la compañía, que según reportes generó 240 millones de dólares en ingresos recurrentes anuales en 2025, y whose CEO, Aidan Gomez, ha mencionado una posible salida a bolsa "próximamente".\n\nSeguí leyendo en este enlace: https://techcrunch.com/2026/03/26/cohere-launches-an-open-source-voice-model-specifically-for-transcription/\n\n---\n\n### **Nvidia Presenta DLSS 5: IA Generativa para Elevar el Realismo en Videojuegos y Más Allá**\n\n![**Nvidia Presenta DLSS 5: IA Generativa para Elevar el Realismo en Videojuegos y Más Allá**](https://techcrunch.com/wp-content/uploads/2026/03/nvidia-dlss-5.jpeg?resize=1200,675)\n\n**Nvidia Presenta DLSS 5: IA Generativa para Elevar el Realismo en Videojuegos y Más Allá**\n\nDurante la conferencia magistral de Nvidia en el evento GTCon, el CEO Jensen Huang anunció DLSS 5, la próxima evolución de la tecnología de gráficos impulsada por inteligencia artificial de la compañía. Esta nueva versión busca un avance significativo en el realismo de los videojuegos, pero con un enfoque que trasciende el entretenimiento digital. DLSS 5 fusiona los datos estructurados tradicionales de los gráficos 3D con modelos de IA generativa que predicen y completan partes de la imagen, permitiendo a las GPU de Nvidia escenas detalladas y personajes convincentes sin renderizar cada elemento desde cero, optimizando así el uso de potencia computacional. Huang lo describió como la unión de "gráficos 3D controlables, la verdad fundamental de los mundos virtuales" con "IA generativa, computación probabilística", señalando que esta combinación ofrece contenido "hermoso, asombroso y, lo más importante, controlable".\n\nAunque el sector del gaming representa hoy una porción menor de los ingresos de Nvidia en comparación con su historia, fue esta industria la que catapultó a la compañía. Huang enmarcó el enfoque de DLSS 5 como un ejemplo de un cambio de paradigma computacional más amplio. Su ambición es aplicar esta arquitectura que combina datos estructurados y generativos mucho más allá de los videojuegos, extendiéndose a la informática empresarial. El ejecutivo citó plataformas de datos corporativos como Snowflake, Databricks y BigQuery como ejemplos de conjuntos de datos estructurados que futuros sistemas de IA podrían analizar y de los cuales generar insights. "En el futuro, lo que sucederá es que estas estructuras de datos serán utilizadas por la IA, y la IA será mucho, mucho más rápida que nosotros", afirmó Huang, sugiriendo que los agentes autónomos del futuro interactuarán tanto con bases de datos estructuradas como con lo que denominó la "base de datos generativa", que representa la gran mayoría del mundo. Esta visión posiciona a DLSS 5 no solo como un hito técnico para el rendering, sino como un prototipo de una nueva forma de interacción entre la IA y los datos en escala industrial.\n\nConocé más en este enlace: https://techcrunch.com/2026/03/16/nvidias-dlss-5-uses-generative-ai-to-boost-photo-realism-in-video-games-with-ambitions-beyond-gaming/\n\n---\n\n### **DLSS 5: La IA de Nvidia redibuja el renderizado 3D en tiempo real, pero divide a la comunidad**\n\n**DLSS 5: La IA de Nvidia redibuja el renderizado 3D en tiempo real, pero divide a la comunidad**\n\nNvidia ha presentado DLSS 5, la próxima evolución de su tecnología de superresolución impulsada por inteligencia artificial, alejándose significativamente de su función original de upscaling. Este nuevo sistema, denominado "modelo de renderizado neuronal guiado en 3D", no se limita a aumentar la resolución de una imagen, sino que modifica proactivamente elementos fundamentales de la escena en tiempo real, como la iluminación, los materiales y las sombras, durante el proceso de renderizado del juego. Este avance, que promete un salto cualitativo en la fidelidad fotográfica, ha generado una reacción inmediata y polarizada dentro de la comunidad de jugadores y desarrolladores.\n\nLa demostración técnica, mostrada en títulos como *Resident Evil Requiem*, ha sido el foco de las críticas. Varios usuarios han señalado que los personajes y entornos pierden la estética y el estilo artístico original, adoptando un aspecto excesivamente realista o "yassificado" que, para muchos, distorsiona la visión creativa de los artistas. Este fenómeno ha dado lugar a una avalancha de memes y quejas en redes sociales, cuestionando si la tecnología ha cruzado un límite al imponer su propia interpretación estética sobre el trabajo de diseño. Frente a esto, Nvidia defiende que el sistema está diseñado para "honrar la intención original de los artistas", argumentando que su modelo de IA ha sido entrenado para comprender y complementar, no reemplazar, las decisiones de iluminación y materiales establecidas en el desarrollo.\n\nEl impacto potencial de DLSS 5 es profundo. Técnicamente, representa un cambio de paradigma al integrar la reconstrucción de imagen con la generación de componentes de la escena, lo que podría permitir a los desarrolladores alcanzar niveles de realismo antes impensables sin un coste de rendimiento prohibitivo. Sin embargo, su recepción subraya una tensión creciente en la industria: el equilibrio entre la innovación tecnológica y la preservación de la identidad artística. La aceptación de esta herramienta dependerá en gran medida de cómo los estudios d

In [15]:
print("💾 [4/4] Guardando resultados...")
Path(OUT_PATH).write_text(article, encoding="utf-8")
csv_path = Path(OUT_PATH).with_suffix(".csv")
csv_path.write_text(df_res.to_csv(index=False), encoding="utf-8")
print(f"   → Guardado {OUT_PATH} y {csv_path.name}")

print("✅ Pipeline finalizado con éxito.")

💾 [4/4] Guardando resultados...
   → Guardado outputs/Highlights_AI_marzo_26_20260331_095215.txt y Highlights_AI_marzo_26_20260331_095215.csv
✅ Pipeline finalizado con éxito.

In [16]:
# Total de tokens usados en todo el pipeline
if llm_client and hasattr(llm_client, "token_summary"):
    print("📊 Token usage total del pipeline:")
    print("  ", llm_client.token_summary())
else:
    print("No LLM client disponible — no hay tokens que reportar.")

📊 Token usage total del pipeline:
   Tokens usados — prompt: 30,416 | completion: 49,409 | total: 79,825